using LabMaster.Data;
using Microsoft.Data.SqlClient;
namespace LabMaster.Services;
public sealed class AnalyzerService
{
 public async Task<List<AnalyzerRow>> GetAsync(){await using var c=Database.CreateConnection();await c.OpenAsync();const string s="SELECT a.AnalyzerId,a.AnalyzerCode,a.AnalyzerName,d.DepartmentName,a.Manufacturer,a.Model,a.SerialNumber,a.ConnectionType,a.IsActive,a.LastCalibrationDate,a.NextCalibrationDate,a.Notes FROM dbo.Analyzers a LEFT JOIN dbo.Departments d ON d.DepartmentId=a.DepartmentId ORDER BY a.AnalyzerName";await using var cmd=new SqlCommand(s,c);await using var r=await cmd.ExecuteReaderAsync();var x=new List<AnalyzerRow>();while(await r.ReadAsync())x.Add(new AnalyzerRow(r.GetInt32(0),r.GetString(1),r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.GetBoolean(8),r.IsDBNull(9)?null:r.GetDateTime(9),r.IsDBNull(10)?null:r.GetDateTime(10),r.IsDBNull(11)?null:r.GetString(11)));return x;}
 public async Task AddAsync(string code,string name,int? departmentId,string? manufacturer,string? model,string? serial,string? connection,DateTime? lastCalibration,DateTime? nextCalibration,string? notes){await using var c=Database.CreateConnection();await c.OpenAsync();const string s="INSERT dbo.Analyzers(AnalyzerCode,AnalyzerName,DepartmentId,Manufacturer,Model,SerialNumber,ConnectionType,LastCalibrationDate,NextCalibrationDate,Notes) VALUES(@c,@n,@d,@m,@mo,@sn,@ct,@lc,@nc,@no)";await using var cmd=new SqlCommand(s,c);cmd.Parameters.AddWithValue("@c",code.Trim());cmd.Parameters.AddWithValue("@n",name.Trim());cmd.Parameters.AddWithValue("@d",(object?)departmentId??DBNull.Value);cmd.Parameters.AddWithValue("@m",(object?)manufacturer??DBNull.Value);cmd.Parameters.AddWithValue("@mo",(object?)model??DBNull.Value);cmd.Parameters.AddWithValue("@sn",(object?)serial??DBNull.Value);cmd.Parameters.AddWithValue("@ct",(object?)connection??DBNull.Value);cmd.Parameters.AddWithValue("@lc",(object?)lastCalibration??DBNull.Value);cmd.Parameters.AddWithValue("@nc",(object?)nextCalibration??DBNull.Value);cmd.Parameters.AddWithValue("@no",(object?)notes??DBNull.Value);await cmd.ExecuteNonQueryAsync();}
 public async Task SetActiveAsync(int id,bool active){await using var c=Database.CreateConnection();await c.OpenAsync();await using var cmd=new SqlCommand("UPDATE dbo.Analyzers SET IsActive=@a WHERE AnalyzerId=@id",c);cmd.Parameters.AddWithValue("@a",active);cmd.Parameters.AddWithValue("@id",id);await cmd.ExecuteNonQueryAsync();}
}
public record AnalyzerRow(int Id,string Code,string Name,string? Department,string? Manufacturer,string? Model,string? SerialNumber,string? ConnectionType,bool Active,DateTime? LastCalibration,DateTime? NextCalibration,string? Notes);