using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Win32;

namespace LabMaster.Services;

public sealed class LicenseService
{
    // Replace this with the production public key generated by the Lab Master license issuer.
    // Never place the private signing key inside the application.
    const string PublicKeyPem = @"-----BEGIN PUBLIC KEY-----
REPLACE_WITH_LAB_MASTER_PUBLIC_KEY
-----END PUBLIC KEY-----";

    static readonly string LicenseDirectory =
        Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "LabMaster");
    static readonly string LicensePath = Path.Combine(LicenseDirectory, "license.key");

    public LicenseStatus GetStatus()
    {
        try
        {
            if (!File.Exists(LicensePath))
                return LicenseStatus.Inactive("Activation required.");

            var token = File.ReadAllText(LicensePath).Trim();
            if (!TryVerify(token, out var license))
                return LicenseStatus.Inactive("Invalid activation key.");

            if (!string.Equals(license.Product, "LabMaster", StringComparison.Ordinal))
                return LicenseStatus.Inactive("Invalid product license.");

            if (!string.Equals(license.MachineId, GetMachineId(), StringComparison.Ordinal))
                return LicenseStatus.Inactive("This activation key belongs to another PC.");

            if (DateTimeOffset.UtcNow > license.ExpiresAt)
                return LicenseStatus.Inactive("Activation key has expired.");

            return LicenseStatus.Active(license);
        }
        catch (Exception ex)
        {
            return LicenseStatus.Inactive("License check failed: " + ex.Message);
        }
    }

    public bool Activate(string token, out string message)
    {
        token = token.Trim();
        if (!TryVerify(token, out var license))
        {
            message = "Invalid activation key.";
            return false;
        }

        if (!string.Equals(license.Product, "LabMaster", StringComparison.Ordinal))
        {
            message = "This key is not for Lab Master.";
            return false;
        }

        if (!string.Equals(license.MachineId, GetMachineId(), StringComparison.Ordinal))
        {
            message = "This activation key belongs to another PC.";
            return false;
        }

        if (DateTimeOffset.UtcNow > license.ExpiresAt)
        {
            message = "This activation key has already expired.";
            return false;
        }

        Directory.CreateDirectory(LicenseDirectory);
        File.WriteAllText(LicensePath, token, Encoding.UTF8);
        message = $"Activation successful. Valid until {license.ExpiresAt:dd-MMM-yyyy}.";
        return true;
    }

    public static string GetMachineId()
    {
        using var key = Registry.LocalMachine.OpenSubKey(@"SOFTWAREMicrosoftCryptography");
        var machineGuid = key?.GetValue("MachineGuid")?.ToString();

        if (string.IsNullOrWhiteSpace(machineGuid))
            machineGuid = Environment.MachineName;

        using var sha = SHA256.Create();
        return Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes("LabMaster|" + machineGuid)));
    }

    static bool TryVerify(string token, out LicensePayload license)
    {
        license = new LicensePayload();
        try
        {
            var parts = token.Split('.');
            if (parts.Length != 2) return false;

            var payloadBytes = Base64UrlDecode(parts[0]);
            var signature = Base64UrlDecode(parts[1]);

            using var rsa = RSA.Create();
            rsa.ImportFromPem(PublicKeyPem);

            if (!rsa.VerifyData(payloadBytes, signature, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1))
                return false;

            var json = Encoding.UTF8.GetString(payloadBytes);
            license = JsonSerializer.Deserialize<LicensePayload>(json) ?? new LicensePayload();
            return true;
        }
        catch
        {
            return false;
        }
    }

    static byte[] Base64UrlDecode(string value)
    {
        value = value.Replace('-', '+').Replace('_', '/');
        switch (value.Length % 4)
        {
            case 2: value += "=="; break;
            case 3: value += "="; break;
        }
        return Convert.FromBase64String(value);
    }
}

public sealed class LicensePayload
{
    public string Product { get; set; } = "";
    public string MachineId { get; set; } = "";
    public DateTimeOffset IssuedAt { get; set; }
    public DateTimeOffset ExpiresAt { get; set; }
    public string LicenseId { get; set; } = "";
}

public sealed record LicenseStatus(bool IsActive, string Message, LicensePayload? License)
{
    public static LicenseStatus Active(LicensePayload license) =>
        new(true, $"Activated until {license.ExpiresAt:dd-MMM-yyyy}", license);

    public static LicenseStatus Inactive(string message) =>
        new(false, message, null);
}