USE LabMasterDb;
GO
IF OBJECT_ID('dbo.Expenses','U') IS NULL
CREATE TABLE dbo.Expenses(
 ExpenseId INT IDENTITY PRIMARY KEY,
 ExpenseDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
 Category NVARCHAR(80) NOT NULL,
 Description NVARCHAR(300) NULL,
 Amount DECIMAL(12,2) NOT NULL,
 PaidTo NVARCHAR(150) NULL,
 PaymentMethod NVARCHAR(30) NOT NULL DEFAULT 'Cash',
 CreatedBy NVARCHAR(100) NULL
);
GO
IF OBJECT_ID('dbo.DoctorShares','U') IS NULL
CREATE TABLE dbo.DoctorShares(
 ShareId INT IDENTITY PRIMARY KEY,
 OrderId INT NOT NULL,
 DoctorName NVARCHAR(150) NOT NULL,
 ShareAmount DECIMAL(12,2) NOT NULL,
 CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
 CONSTRAINT FK_DoctorShares_Order FOREIGN KEY(OrderId) REFERENCES dbo.TestOrders(OrderId)
);
GO